# This script removes all files auto-generated by autotools
# Run make clean to clean up compilation specific files
# After cleaning, you will need to run ./autogen.sh to regenerate them
rm -rf m4/ aclocal.m4 autom4te.cache/ compile depcomp autoscan.log config.guess config.h config.h.in~ config.guess config.status config.sub configure configure.scan missing install-sh stamp-h1 configure.ac~ libtool ltmain.sh
find . -name Makefile -delete
find . -name Makefile.in -delete
