name: Build on Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: autogen
      run: ./autogen.sh

    - name: configure
      run: ./configure

    - name: make
      run: make

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: allnet-linux
        path: bin/
