name: Build on MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup automake
      run: |
        brew install automake
        autoreconf -i

    - name: autogen
      run: ./autogen.sh

    - name: configure
      run: ./configure

    - name: make
      run: make

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: allnet-macos
        path: bin/
